version: '3.7'
services:
  app:
    image: php:8.0-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - PHP_IDE_CONFIG=serverName=Docker

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
 